### ISSUE TITLE
Is it possible to define methods that are not tasks?

### ISSUE THREAD

**Issue by MatheusRich** [ioquatix/bake#5]
I would like to define helper methods that will not be parsed into tasks. Ex:
```ruby
# not a task!
def slugify(str)
  str.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
end

def create_post(post_name)
  File.write(slugify(post_name))
end

```

I don't know if this is possible, but I couldn't find in the docs.

_One alternative, though is defining lambdas and using them._

```ruby
Slugify = ->(str)  { str.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '') }

def create_post(post_name)
  File.write(Slugify.(post_name))
end
```

**Comment by ioquatix** [comment]
Yes, make them `private`.

**Comment by ioquatix** [comment]
I've added some documentation hopefully it's sufficient going forward:

https://ioquatix.github.io/bake/guides/getting-started/index.html#private-methods

**Comment by MatheusRich** [comment]
Perfect!
