### ISSUE TITLE
Can't parse "false"

### ISSUE THREAD

**Issue by madleech** [ioquatix/bake#6]
`Bake::Types::Boolean.parse` only handles truthy values:

```ruby
[4] pry(main)> Bake::Types::Boolean.parse("false")
=> nil
```

This makes it impossible to have tri-state inputs to recipes and handle true/false/nil, e.g. `@param foo [Boolean | Nil]` will only even supply `true` and `nil`.

**Comment by ioquatix** [comment]
Ah, that seems like a reasonable request. Do you want to make a PR to fix this? Otherwise I'm happy to do it.

**Comment by ioquatix** [comment]
I had a few moments and so I took a stab at implementing it.
